### ISSUE TITLE
Create sequence

### ISSUE THREAD

**Issue by RalphJohn5** [Michelle20Anne/Team-2#10]

**Comment by RalphJohn5** [comment]
![examples](https://user-images.githubusercontent.com/94658663/145500231-4aff6bfb-a59b-4638-b30c-444aa6938193.png)
Second Graph for Sequence

**Comment by kmjzmn** [comment]
![SEQUENCE](https://user-images.githubusercontent.com/94656891/145500233-73f67468-7748-41b7-a6f7-99b56e4021e1.png)
### First Graph for Sequence
