### ISSUE TITLE
Practice Crud

### ISSUE THREAD

**Issue by MichelleAnneMaturan** [Michelle20Anne/Team-2#15]

**Comment by AlfredGuiller** [comment]
Crud

**Comment by AlfredGuiller** [comment]
![271828643_1859519767584546_8249451576502887465_n](https://user-images.githubusercontent.com/94514879/149646151-fe6a45a8-c918-4ef5-b1c3-a75b6ab780ab.gif)
![271939506_887965831873592_7904667496728879960_n](https://user-images.githubusercontent.com/94514879/149646153-773a9c64-4aa6-4958-af18-134a3db969d3.gif)
