### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by MichelleAnneMaturan** [Michelle20Anne/Team-2#18]

**Comment by kmjzmn** [comment]
![WIREFRAME](https://user-images.githubusercontent.com/94656891/148947941-0016850c-2599-4e7e-be31-15898c211dea.png)

**Comment by kmjzmn** [comment]
![WIREFRAME LOGIN PAGE](https://user-images.githubusercontent.com/94656891/148951907-92b923ae-9a0f-43d6-a316-b3bf68ac33ea.png)
