### ISSUE TITLE
Finalize low level 

### ISSUE THREAD

**Issue by RalphJohn5** [Michelle20Anne/Team-2#3]

**Comment by Jeydl** [comment]
![Uploading LOW LEVEL DIAGRAM.png…]()

**Comment by Jeydl** [comment]
![LOW LEVEL DIAGRAM](https://user-images.githubusercontent.com/94657491/145399298-411e588a-9a73-4919-8a9d-97319efd12b3.png)

**Comment by Jeydl** [comment]
![LOW LEVEL DIAGRAM UPDATED](https://user-images.githubusercontent.com/94657491/145426142-cd95bdaa-e7ed-41ea-8ea8-3f792a6e307e.png)
UPDATED LOW LEVEL DIAGRAM
